services:
  backend:
    build:
      context: ./backend
    image: coffeebaba/anyhabit-backend:latest
  frontend:
    build:
      context: ./frontend
    image: coffeebaba/anyhabit-frontend:latest

